version: "3"
services:
    database:
        image: "mysql:5.7.24"
        restart: always
        container_name: "todo-database"
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - wpsite
        environment:
            MYSQL_ROOT_PASSWORD: "test"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test"
            MYSQL_DATABASE: "test"
    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: password 
        networks:
            - wpsite
            
networks:
    wpsite:
volumes:
    db_data: {}