/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IconPlus {
    }
    interface UiButton {
        "type"?: "button" | "submit" | "reset";
    }
    interface UiInput {
        "placeholder"?: string;
        "value": string;
    }
}
declare global {
    interface HTMLIconPlusElement extends Components.IconPlus, HTMLStencilElement {
    }
    var HTMLIconPlusElement: {
        prototype: HTMLIconPlusElement;
        new (): HTMLIconPlusElement;
    };
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiInputElement extends Components.UiInput, HTMLStencilElement {
    }
    var HTMLUiInputElement: {
        prototype: HTMLUiInputElement;
        new (): HTMLUiInputElement;
    };
    interface HTMLElementTagNameMap {
        "icon-plus": HTMLIconPlusElement;
        "ui-button": HTMLUiButtonElement;
        "ui-input": HTMLUiInputElement;
    }
}
declare namespace LocalJSX {
    interface IconPlus {
    }
    interface UiButton {
        "onClicked"?: (event: CustomEvent<any>) => void;
        "type"?: "button" | "submit" | "reset";
    }
    interface UiInput {
        "onAccept"?: (event: CustomEvent<any>) => void;
        "onChanged"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "icon-plus": IconPlus;
        "ui-button": UiButton;
        "ui-input": UiInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "icon-plus": LocalJSX.IconPlus & JSXBase.HTMLAttributes<HTMLIconPlusElement>;
            "ui-button": LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            "ui-input": LocalJSX.UiInput & JSXBase.HTMLAttributes<HTMLUiInputElement>;
        }
    }
}
