/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IconPlus {
    }
    interface UiButton {
        "type"?: "button" | "submit" | "reset";
    }
    interface UiCheckbox {
        "checked"?: boolean;
    }
    interface UiInput {
        "placeholder"?: string;
        "value": string;
    }
    interface UiListItem {
    }
}
declare global {
    interface HTMLIconPlusElement extends Components.IconPlus, HTMLStencilElement {
    }
    var HTMLIconPlusElement: {
        prototype: HTMLIconPlusElement;
        new (): HTMLIconPlusElement;
    };
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiCheckboxElement extends Components.UiCheckbox, HTMLStencilElement {
    }
    var HTMLUiCheckboxElement: {
        prototype: HTMLUiCheckboxElement;
        new (): HTMLUiCheckboxElement;
    };
    interface HTMLUiInputElement extends Components.UiInput, HTMLStencilElement {
    }
    var HTMLUiInputElement: {
        prototype: HTMLUiInputElement;
        new (): HTMLUiInputElement;
    };
    interface HTMLUiListItemElement extends Components.UiListItem, HTMLStencilElement {
    }
    var HTMLUiListItemElement: {
        prototype: HTMLUiListItemElement;
        new (): HTMLUiListItemElement;
    };
    interface HTMLElementTagNameMap {
        "icon-plus": HTMLIconPlusElement;
        "ui-button": HTMLUiButtonElement;
        "ui-checkbox": HTMLUiCheckboxElement;
        "ui-input": HTMLUiInputElement;
        "ui-list-item": HTMLUiListItemElement;
    }
}
declare namespace LocalJSX {
    interface IconPlus {
    }
    interface UiButton {
        "onButton-clicked"?: (event: CustomEvent<any>) => void;
        "type"?: "button" | "submit" | "reset";
    }
    interface UiCheckbox {
        "checked"?: boolean;
        "onCheckbox-change"?: (event: CustomEvent<any>) => void;
    }
    interface UiInput {
        "onInput-accept"?: (event: CustomEvent<any>) => void;
        "onInput-changed"?: (event: CustomEvent<any>) => void;
        "placeholder"?: string;
        "value"?: string;
    }
    interface UiListItem {
    }
    interface IntrinsicElements {
        "icon-plus": IconPlus;
        "ui-button": UiButton;
        "ui-checkbox": UiCheckbox;
        "ui-input": UiInput;
        "ui-list-item": UiListItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "icon-plus": LocalJSX.IconPlus & JSXBase.HTMLAttributes<HTMLIconPlusElement>;
            "ui-button": LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            "ui-checkbox": LocalJSX.UiCheckbox & JSXBase.HTMLAttributes<HTMLUiCheckboxElement>;
            "ui-input": LocalJSX.UiInput & JSXBase.HTMLAttributes<HTMLUiInputElement>;
            "ui-list-item": LocalJSX.UiListItem & JSXBase.HTMLAttributes<HTMLUiListItemElement>;
        }
    }
}
